### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-learning-resources#2]
add i18n 

https://gohugo.io/content-management/multilingual/
https://gohugo.io/functions/i18n/

**Comment by xavier506** [comment]
@JustinCast  this is what teh console show when I run the site locally, there are two instances running for `es` and `en` 
```
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/en/ (bind address 127.0.0.1)
Environment: "development"
Web Server is available at http://localhost:1314/es/ (bind address 127.0.0.1)
```

**Comment by xavier506** [comment]
Github Pages config

![image](https://user-images.githubusercontent.com/5632966/77241935-01b84300-6bbf-11ea-9355-52971ac059f8.png)

**Comment by JustinCast** [comment]
Is that two instances actually an issue?

**Comment by JustinCast** [comment]
https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost

**Comment by JustinCast** [comment]
I think translation by content directory could be a good approach; better to maintain.
https://gohugo.io/content-management/multilingual/#translation-by-content-directory
